### ISSUE TITLE
Request: change directional buttons

### ISSUE THREAD

**Issue by rorosaurus** [ginkage/FlippAirMouse#2]
I think this layout would be the most intuitive and functional!

Left: Left Click
Right: Right Click
Center: Middle Click
Up: Scroll Up
Down: Scroll Down
Back: Return to Menu

**Comment by ginkage** [comment]
This makes little sense without also rotating the coordinate system so that you're pointing towards the screen with the add-on module. I find it a lot more comfortable to hold it like a remote, with the USB port pointing the screen, and in that orientation it's more intuitive to use the current layout.

**Comment by rorosaurus** [comment]
Ahh, you're right! I forgot to account for the rotation of the device. That orientation makes much more sense.

My new proposed button use:
Left: Scroll Down
Right: Scroll Up
Center: Middle Click
Up: Left Click
Down: Right Click
Back: Return to Menu

I'll update the PR! (And compile+test once my add-on arrives!)

**Comment by rorosaurus** [comment]
PR #3 now includes this revised button layout!

**Comment by ginkage** [comment]
Sorry, I'm a bit slow, mostly because 'tis the season, I'll definitely test the PR soon.

**Comment by ginkage** [comment]
Anyway, should be all good now, merged and adjusted for better usability. :)
